### ISSUE TITLE
关于Audio Source和Pose Source

### ISSUE THREAD

**Issue by old-fan-kk** [Hangz-nju-cuhk/Talking-Face_PC-AVS#11]
您好，请问一下在训练过程中Audio Source和Pose Source是来自同一个视频吗？

**Comment by Hangz-nju-cuhk** [comment]
Hi, 是的，不然没有办法监督。

**Comment by old-fan-kk** [comment]
那这不是输入就是输出了吗

**Comment by Hangz-nju-cuhk** [comment]
是的就是这样，建议去看一下paper哦

**Comment by old-fan-kk** [comment]
感谢回复，我感觉这样是不是容易过拟合，网络什么也不用做直接把输入作为输出就行了

**Comment by Hangz-nju-cuhk** [comment]
这边需要担心的问题并不是过拟合，而是如何让audio信息起作用，可以看一下文章中为了解决这个问题我们的设计。

**Comment by old-fan-kk** [comment]
感谢感谢!!
