### ISSUE TITLE
Training code will be released?

### ISSUE THREAD

**Issue by Rudrabha** [Hangz-nju-cuhk/Talking-Face_PC-AVS#12]
Hi,

Congratulations on this great work and thanks for releasing the codes! The results are mighty impressive! Any plans on releasing the training code too?

**Comment by Hangz-nju-cuhk** [comment]
Hi, thank you for your interest. The training code might be released later. But actually, the losses and codes for different modules during training are available in `models/av_model.py`.

**Comment by Rudrabha** [comment]
Thanks a lot. I will have a look at those.

**Comment by xiao-keeplearning** [comment]
Hi, Is there any plan to relase the training code？ I  I can't wait it.
