### ISSUE TITLE
关于训练集

### ISSUE THREAD

**Issue by old-fan-kk** [Hangz-nju-cuhk/Talking-Face_PC-AVS#18]
您好，请问一下，对于vox2数据集，训练集包含多少个speaker，您是随机选取的吗

**Comment by Hangz-nju-cuhk** [comment]
我使用了官方的train test split，可以直接参考voxceleb2的官网

**Comment by old-fan-kk** [comment]
您好，训练集中的5994个speaker您都使用了吗？

**Comment by Hangz-nju-cuhk** [comment]
@old-fan-kk 是的，我没有做特别的挑选。

**Comment by old-fan-kk** [comment]
感谢，明白了
