### ISSUE TITLE
Wrong Paper link

### ISSUE THREAD

**Issue by DaddyJin** [Hangz-nju-cuhk/Talking-Face_PC-AVS#2]
The paper link of the corresponding CVPR21 paper is linked to your previous AAAI19 paper DIVS.
@Hangz-nju-cuhk

**Comment by KelestZ** [comment]
+1

**Comment by Hangz-nju-cuhk** [comment]
Thank you for your interest! The paper is on arXiv now. I just could not wait to push the code on a few days ago thus you guys could see the code before the paper is released :).

**Comment by DaddyJin** [comment]
Thank you for your great work.
