### ISSUE TITLE
About constrast learning

### ISSUE THREAD

**Issue by NNNNAI** [Hangz-nju-cuhk/Talking-Face_PC-AVS#23]
Thanks for sharing your work! Where is the sricpt for constrast learning for image feature and audio feature. I found a class in "models\networks\loss.py": SoftmaxContrastiveLoss, is this the realization of contrast learning?

**Comment by Hangz-nju-cuhk** [comment]
Hi, you are correct!

**Comment by NNNNAI** [comment]
Thanks for your help!,BTW, what value do you set for augment num_inputs during training? Because I noticed that this augment is used in line 49 of models\networks\vision_network.py.

**Comment by Hangz-nju-cuhk** [comment]
The num_inputs is fixed as 1 during the whole training and testing.

**Comment by NNNNAI** [comment]
Issue has been solved!
