### ISSUE TITLE
can you share the details of the augmentation generating non-id space

### ISSUE THREAD

**Issue by makpia** [Hangz-nju-cuhk/Talking-Face_PC-AVS#38]
i notice that you mentioned the paper "Neural Head Reenactment with Latent Pose Descriptors" in an issue about non-id space. i tried the augmentation used in their code, but it seems different from yours, with fewer changes.
this part seems vital considering the non-id space is vital, promising the model to distangle the id feature and pose feature. so i would like to know the augmentation details in your paper. can you share it to us?

**Comment by Hangz-nju-cuhk** [comment]
Hi, the code for our augmentation is already in `data/base_dataset.py`. I think it can also work if you use their augmentation. The reason that the augmentations are different is that their code was not publically available when I was working on this one.

**Comment by makpia** [comment]
> Hi, the code for our augmentation is already in `data/base_dataset.py`. I think it can also work if you use their augmentation. The reason that the augmentations are different is that their code was not publically available when I was working on this one.

thanks for the reply! i missed the part in this file. i will try it later. thank you!
