### ISSUE TITLE
Questions about the demo video in project page

### ISSUE THREAD

**Issue by DaddyJin** [Hangz-nju-cuhk/Talking-Face_PC-AVS#39]
In the demo video on the project page, there are generated faces of Obama and Biden，of time stamp 2:26.
![image](https://user-images.githubusercontent.com/22629481/130021594-b634b4a5-7eea-4242-b4a4-c182c4be97a4.png)
It seems that there exists a little **identity mismatch** problem, which may be a potential improvement direction.
Could you please tell us the source videos you use in this situation or the location  in  VoxCeleb2(maybe) for better reference?
Thanks in advance and appreciate the great work PC-AVS!

**Comment by Hangz-nju-cuhk** [comment]
Hi, yes indeed there is the identity mismatch problem which I also think is worth exploring. 

For generating these videos, we use actually only two photos as identity references as shown before this video. These two photos are directly found on the internet, from their speeches.

**Comment by DaddyJin** [comment]
Appreciate the reply. Have a good day!
