### ISSUE TITLE
 LRW + VoxCeleb

### ISSUE THREAD

**Issue by Yingying6** [Hangz-nju-cuhk/Talking-Face_PC-AVS#46]
Hi Hang, did you combine the two dataset for training the lip-sync and test separately on each, or did you separate the training dataset - i wonder if voxceleb2 alone can achieve the good performance in terms of the lip-sync.
Thanks.

**Comment by Hangz-nju-cuhk** [comment]
Voxceleb2 alone can already achieve good lip-sync performance. Our model is finetuned on LRW to improve the generation quality.
