### ISSUE TITLE
How to calculate the file "demo.csv"  parameters （160， 363）？

### ISSUE THREAD

**Issue by DWCTOD** [Hangz-nju-cuhk/Talking-Face_PC-AVS#5]
Hi, thanks for your greate work.
what about the parameters in file "demo.csv" (160, 363)

`misc/Input/517600055 1 misc/Pose_Source/517600078 160 misc/Audio_Source/681600002.mp3 misc/Mouth_Source/681600002 363 dummy`

**Comment by Hangz-nju-cuhk** [comment]
Hi, please refer to the README "Prepare Testing Meta Data" part. 160 is the number of driving pose frames, and actually, only this number is used in the dataloader.

**Comment by DWCTOD** [comment]
> Hi, please refer to the README "Prepare Testing Meta Data" part. 160 is the number of driving pose frames, and actually, only this number is used in the dataloader.

Thanks very much.
what should I process the input image?
![image](https://user-images.githubusercontent.com/41478810/116074110-dfe39680-a6c3-11eb-96a2-6dfd20164d61.png)

**Comment by Hangz-nju-cuhk** [comment]
Please refer to the "Self-Prepared Data Processing" part. Please thoroughly read the README before raising any issues. Manual alignment is also applicable. You have to make sure the figure is aligned in the same way as the training set. Plus, as there are seldom any Asia faces in the training set, there is a possibility that the result will not work as shown in the demo.

**Comment by DWCTOD** [comment]
> Please refer to the "Self-Prepared Data Processing" part. Please thoroughly read the README before raising any issues. Manual alignment is also applicable. You have to make sure the figure is aligned in the same way as the training set. Plus, as there are seldom any Asia faces in the training set, there is a possibility that the result will not work as shown in the demo.

非常抱歉，刚开始的时候没有注意看。以为只要输入的图片是对齐过的就行了，然后这里本来自己使用了dlib 对齐，发现好像有点问题。
