### ISSUE TITLE
Running code on own image?

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [Hangz-nju-cuhk/Talking-Face_PC-AVS#7]
Hello, 
I have configured the project as suggested here. I am able to run it on the demo images placed inside ./misc/input/some_id 
My question is how can I run the project on my own image. 

For example when I am creating a folder inside ./misc/input/ of name 123456 and then placing my own image of size 224x224 inside it with name 000000.jpg (the complete path is ./misc/input/123456/000000.jpg), and then after changing the demo.csv file when I am running the code then I am not getting desired results.

Please help me.

**Comment by Hangz-nju-cuhk** [comment]
Please refer to README [https://github.com/Hangz-nju-cuhk/Talking-Face_PC-AVS#self-prepared-data-processing](url).

**Comment by mayanktiwariiiitdmj** [comment]
thank you sir, the problem is solved now...
