### ISSUE TITLE
Is it possible to do lip sync without audio?

### ISSUE THREAD

**Issue by bycloudai** [Hangz-nju-cuhk/Talking-Face_PC-AVS#8]
I'm just curious whether if its possible to just have mouth_source and input to generate a video, where the audio source can be ignored (be None). Similar to how lips sync works. I tested on mine and it didn't work.

Sorry to bother you again. I tried to figure out by looking through the codes but that didn't help.

**Comment by Hangz-nju-cuhk** [comment]
Hi, this is a very good question! The original design of this framework supports this kind of application, just like my first paper (See my first repo). But during the final training stage of this project, we neglect the video stream to ensure that our model performs perfectly given audio conditions only (this is the most important part when formulating this paper). 

Slight audio-visual mixed fine-tuning on the training set should be able to achieve this, and I will try this when I have time. But for now, the model does not support this setting.
